version: '3.8'

services:

  app1:
    build:
      context: ./bigwork_meta
      dockerfile: Dockerfile
    container_name: bigwork_meta_app
    ports:
      - "8082:8082"
      - "8084:8084"
    environment:
      SPRING_REDIS_HOST: 62.234.221.226
      SPRING_REDIS_PORT: "6379"  # 连接到 Redis 容器的 6379 端口
    depends_on:
      - redis
    networks:
      - app-network

  app2:
    build:
      context: ./bigwork_apitest
      dockerfile: Dockerfile
    container_name: bigwork_apitest_app
    ports:
      - "8083:8083"
    environment:
      SPRING_REDIS_HOST: 62.234.221.226
      SPRING_REDIS_PORT: "6379"  # 连接到 Redis 容器的 6379 端口
    depends_on:
      - redis
    networks:
      - app-network


networks:
  app-network:
    driver: bridge