# 服务器配置
server:
  port: 8083  # 应用程序运行的端口号
  servlet:
    context-path: /apitest
spring:
  datasource:
    username: root
    password: chen160213497
    url: jdbc:mysql://localhost:3306/big_work_db?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    activate:
      on-profile: local
swagger:
  enable: true
mybatis:
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: com.bigwork.bigwork_apitest.model
  config-location: classpath:mybatis-config.xml
config:
  kafka:
    servers: "localhost:9092"

netty:
  port: 8084