# 服务器配置
server:
  port: 8083  # 应用程序运行的端口号
  servlet:
    context-path: /apitest
spring:
  datasource:
    username: fangchen
    password: "chen160213497"
    url: jdbc:mysql://localhost:3307/big_work_db
    driver-class-name: com.mysql.cj.jdbc.Driver
swagger:
  enable: true
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.bigwork.bigwork_apitest.model
