# 服务器配置
server:
  port: 8083  # 应用程序运行的端口号
  servlet:
    context-path: /apitest
spring:
  datasource:
    username: root
    password: "chen160213497"
    url: jdbc:mysql://localhost:3306/big_work_db?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
swagger:
  enable: true
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.starter.bigwork_apitest.model

Netty:
  port: 8084