name: Docker Build and Deploy

on:
  push:
    branches:
      - iteration/*  # 只在 iteration/* 分支的 push 事件触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # 使用 GitHub 托管的 Ubuntu 运行器
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 拉取代码

      - name: Display commit info
        run: |
          echo "Commit SHA: ${{ github.sha }}"
          echo "Commit message: ${{ github.event.head_commit.message }}"
          echo "Committer: ${{ github.event.head_commit.author.name }}"

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'  # 设置 Java 17 环境

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-Linux-${{ hashFiles('**/pom.xml') }}  # 基于 pom.xml 的哈希值
          restore-keys: |
            maven-Linux-  # 通用缓存键

      - name: reset to newest commit
        run: |
          git fetch
          git reset --hard ${{github.sha}}
          git status

      - name: Build sources
        run: |
          git status
          mvn clean install -e

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}  # Docker Hub 用户名
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}  # Docker Hub 密码

      - name: Build and push bigwork_meta image
        uses: docker/build-push-action@v2
        with:
          context: ./bigwork_meta  # Docker 构建上下文
          push: true  # 推送镜像到 Docker Hub
          tags: monet12345/bigwork_meta:meta  # 镜像标签

      - name: Build and push bigwork_apitest image
        uses: docker/build-push-action@v2
        with:
          context: ./bigwork_apitest  # Docker 构建上下文
          push: true  # 推送镜像到 Docker Hub
          tags: monet12345/bigwork_apitest:apitest  # 镜像标签

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push  # 依赖 build-and-push 任务
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 拉取代码

      - name: Sync files to server
        run: |
          rsync -avz --delete . ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_PASSWORD }}:~/bigwork/bigwork

      - name: Deploy to server
        uses: appleboy/ssh-action@master  # 使用 SSH 连接到服务器
        with:
          host: ${{ secrets.SERVER_HOST }}  # 服务器 IP 或域名
          username: ${{ secrets.SERVER_USERNAME }}  # 服务器用户名
          password: ${{ secrets.SERVER_PASSWORD }}  # 服务器密码
          script: |
            docker-compose down --remove-orphans
            docker-compose up -d